// Code generated by scripts/gen_core_ifaces.py. DO NOT EDIT.

package sdk

import (
	"context"

	sdkv1 "github.com/WaterGodFurina/Astrbot-go-plugin-sdk/gen/sdkv1"
)

// PluginService is the host->plugin operation surface, implemented by serviceServer.
type PluginService interface {
	Register(context.Context, *sdkv1.RegisterRequest) (*sdkv1.RegisterResponse, error)
	HandleCommand(context.Context, *sdkv1.HandleCommandRequest) (*sdkv1.HandleCommandResponse, error)
	HandleFilter(context.Context, *sdkv1.HandleFilterRequest) (*sdkv1.HandleFilterResponse, error)
	HandleHook(context.Context, *sdkv1.HandleHookRequest) (*sdkv1.HookResponse, error)
	HandleLLMRequest(context.Context, *sdkv1.HandleLLMRequestRequest) (*sdkv1.HandleLLMRequestResponse, error)
	HandleTool(context.Context, *sdkv1.HandleToolRequest) (*sdkv1.HandleToolResponse, error)
	ListTools(context.Context, *sdkv1.PluginRef) (*sdkv1.ListToolsResponse, error)
	ListWebApis(context.Context, *sdkv1.PluginRef) (*sdkv1.ListWebApisResponse, error)
	HandleWebRequest(context.Context, *sdkv1.HandleWebRequestRequest) (*sdkv1.HandleWebRequestResponse, error)
	HealthCheck(context.Context, *sdkv1.Empty) (*sdkv1.HealthResponse, error)
	SetLogLevel(context.Context, *sdkv1.SetLogLevelRequest) (*sdkv1.Empty, error)
	FeedSessionWait(context.Context, *sdkv1.FeedSessionWaitRequest) (*sdkv1.FeedSessionWaitResponse, error)
	GetConfigSchema(context.Context, *sdkv1.PluginRef) (*sdkv1.GetConfigSchemaResponse, error)
	Cleanup(context.Context, *sdkv1.PluginRef) (*sdkv1.Empty, error)
	FeedCronJob(context.Context, *sdkv1.FeedCronJobRequest) (*sdkv1.FeedCronJobResponse, error)
	ManagePlugin(context.Context, *sdkv1.ManagePluginRequest) (*sdkv1.ManagePluginResponse, error)
}

// HostService is the plugin->host reverse-call surface. The gRPC transport
// adapts the generated client to it; the Native transport uses hostServiceServer
// in-process directly.
type HostService interface {
	CallAction(context.Context, *sdkv1.CallActionRequest) (*sdkv1.CallActionResponse, error)
	SendMessage(context.Context, *sdkv1.SendMessageRequest) (*sdkv1.Empty, error)
	RecallMessage(context.Context, *sdkv1.RecallMessageRequest) (*sdkv1.Empty, error)
	GetConfig(context.Context, *sdkv1.GetConfigRequest) (*sdkv1.GetConfigResponse, error)
	SetConfig(context.Context, *sdkv1.SetConfigRequest) (*sdkv1.Empty, error)
	ChatLLM(context.Context, *sdkv1.ChatLLMRequest) (*sdkv1.ChatLLMResponse, error)
	React(context.Context, *sdkv1.ReactRequest) (*sdkv1.Empty, error)
	TextToImage(context.Context, *sdkv1.TextToImageRequest) (*sdkv1.TextToImageResponse, error)
	HtmlRender(context.Context, *sdkv1.HtmlRenderRequest) (*sdkv1.HtmlRenderResponse, error)
	GetCurrConversationID(context.Context, *sdkv1.ConversationIDRequest) (*sdkv1.ConversationIDResponse, error)
	NewConversation(context.Context, *sdkv1.NewConversationRequest) (*sdkv1.ConversationIDResponse, error)
	GetConversation(context.Context, *sdkv1.GetConversationRequest) (*sdkv1.ConversationResponse, error)
	GetConversations(context.Context, *sdkv1.GetConversationsRequest) (*sdkv1.ConversationsResponse, error)
	DeleteConversation(context.Context, *sdkv1.DeleteConversationRequest) (*sdkv1.Empty, error)
	SwitchConversation(context.Context, *sdkv1.SwitchConversationRequest) (*sdkv1.Empty, error)
	UpdateConversationTitle(context.Context, *sdkv1.UpdateConversationTitleRequest) (*sdkv1.Empty, error)
	UpdateConversationPersonaID(context.Context, *sdkv1.UpdateConversationPersonaRequest) (*sdkv1.Empty, error)
	GetPersonas(context.Context, *sdkv1.Empty) (*sdkv1.PersonasResponse, error)
	GetDefaultPersona(context.Context, *sdkv1.GetDefaultPersonaRequest) (*sdkv1.PersonaResponse, error)
	GetPersonaTree(context.Context, *sdkv1.Empty) (*sdkv1.PersonaTreeResponse, error)
	ResolveSelectedPersona(context.Context, *sdkv1.ResolvePersonaRequest) (*sdkv1.ResolvePersonaResponse, error)
	ListProviders(context.Context, *sdkv1.ListProvidersRequest) (*sdkv1.ProvidersResponse, error)
	GetUsingProvider(context.Context, *sdkv1.GetUsingProviderRequest) (*sdkv1.ProviderResponse, error)
	SetProvider(context.Context, *sdkv1.SetProviderRequest) (*sdkv1.Empty, error)
	GetProviderModels(context.Context, *sdkv1.GetProviderModelsRequest) (*sdkv1.ProviderModelsResponse, error)
	GetPluginRegistry(context.Context, *sdkv1.Empty) (*sdkv1.StarsResponse, error)
	GetStar(context.Context, *sdkv1.GetStarRequest) (*sdkv1.StarResponse, error)
	SetPluginEnabled(context.Context, *sdkv1.SetPluginEnabledRequest) (*sdkv1.Empty, error)
	InstallPlugin(context.Context, *sdkv1.InstallPluginRequest) (*sdkv1.Empty, error)
	UninstallPlugin(context.Context, *sdkv1.UninstallPluginRequest) (*sdkv1.Empty, error)
	ListCommandDescriptors(context.Context, *sdkv1.Empty) (*sdkv1.CommandDescriptorsResponse, error)
	ListPlatforms(context.Context, *sdkv1.Empty) (*sdkv1.PlatformsResponse, error)
	RegisterSessionWait(context.Context, *sdkv1.RegisterSessionWaitRequest) (*sdkv1.RegisterSessionWaitResponse, error)
	UnregisterSessionWait(context.Context, *sdkv1.UnregisterSessionWaitRequest) (*sdkv1.Empty, error)
	RegisterBridgeHook(context.Context, *sdkv1.BridgeHookRequest) (*sdkv1.Empty, error)
	UnregisterBridgeHook(context.Context, *sdkv1.BridgeHookRequest) (*sdkv1.Empty, error)
	CreateBlob(context.Context, *sdkv1.CreateBlobRequest) (*sdkv1.CreateBlobResponse, error)
	ReadBlob(context.Context, *sdkv1.ReadBlobRequest) (*sdkv1.ReadBlobResponse, error)
	GetBlobInfo(context.Context, *sdkv1.GetBlobInfoRequest) (*sdkv1.GetBlobInfoResponse, error)
	ReleaseBlob(context.Context, *sdkv1.ReleaseBlobRequest) (*sdkv1.Empty, error)
	ListSkills(context.Context, *sdkv1.Empty) (*sdkv1.SkillsResponse, error)
	SetSkillActive(context.Context, *sdkv1.SetSkillActiveRequest) (*sdkv1.Empty, error)
	DeleteSkill(context.Context, *sdkv1.DeleteSkillRequest) (*sdkv1.Empty, error)
	GetPlatformMessageHistory(context.Context, *sdkv1.GetPMHistoryRequest) (*sdkv1.PMHistoryRecordsResponse, error)
	InsertPlatformMessageHistory(context.Context, *sdkv1.InsertPMHistoryRequest) (*sdkv1.PMHistoryRecordResponse, error)
	UpdatePlatformMessageHistory(context.Context, *sdkv1.UpdatePMHistoryRequest) (*sdkv1.Empty, error)
	DeletePlatformMessageHistory(context.Context, *sdkv1.DeletePMHistoryRequest) (*sdkv1.Empty, error)
	KBRetrieve(context.Context, *sdkv1.KBRetrieveRequest) (*sdkv1.KBRetrieveResponse, error)
	KBUploadFromURL(context.Context, *sdkv1.KBUploadFromURLRequest) (*sdkv1.Empty, error)
	KBListKBs(context.Context, *sdkv1.Empty) (*sdkv1.KBListResponse, error)
	ListSkillsV2(context.Context, *sdkv1.ListSkillsV2Request) (*sdkv1.SkillsResponse, error)
	RegisterFileToken(context.Context, *sdkv1.RegisterFileTokenRequest) (*sdkv1.RegisterFileTokenResponse, error)
	CronCreate(context.Context, *sdkv1.CronCreateRequest) (*sdkv1.CronJobResponse, error)
	CronUpdate(context.Context, *sdkv1.CronUpdateRequest) (*sdkv1.CronJobResponse, error)
	CronDelete(context.Context, *sdkv1.CronDeleteRequest) (*sdkv1.Empty, error)
	CronList(context.Context, *sdkv1.CronListRequest) (*sdkv1.CronJobsResponse, error)
	CronRunNow(context.Context, *sdkv1.CronRunNowRequest) (*sdkv1.Empty, error)
	McpListTools(context.Context, *sdkv1.Empty) (*sdkv1.McpToolsResponse, error)
	McpCallTool(context.Context, *sdkv1.McpCallToolRequest) (*sdkv1.McpCallToolResponse, error)
}
