// Code generated by scripts/gen_core_ifaces.py (see header note). DO NOT EDIT
// without keeping it in sync with the native sdk.HostService interface.

package grpctransport

import (
	"context"

	sdk "github.com/WaterGodFurina/Astrbot-go-plugin-sdk/v2"
	sdkv1 "github.com/WaterGodFurina/Astrbot-go-plugin-sdk/v2/gen/sdkv1"
	sdkv1grpc "github.com/WaterGodFurina/Astrbot-go-plugin-sdk/v2/gen/sdkv1grpc"
	grpc "google.golang.org/grpc"
)

// grpcHostCaller adapts the generated variadic HostServiceClient to the core
// sdk.HostService (native types), so the plugin-side Host wrappers run
// unchanged over gRPC.
type grpcHostCaller struct {
	c    sdkv1grpc.HostServiceClient
	opts []grpc.CallOption
}

var _ sdk.HostService = grpcHostCaller{}

func (a grpcHostCaller) CallAction(ctx context.Context, platform, api string, params map[string]any) (map[string]any, error) {
	resp, err := a.c.CallAction(ctx, &sdkv1.CallActionRequest{Platform: platform, Api: api, ParamsJson: marshalJSON(params)}, a.opts...)
	if err != nil {
		return nil, err
	}
	return unmarshalMap(resp.GetResultJson()), nil
}

func (a grpcHostCaller) SendMessage(ctx context.Context, platform, sessionID string, chain []sdk.Component) error {
	_, err := a.c.SendMessage(ctx, &sdkv1.SendMessageRequest{Platform: platform, SessionId: sessionID, ChainComponents: componentsToProto(chain)}, a.opts...)
	return err
}

func (a grpcHostCaller) RecallMessage(ctx context.Context, platform, messageID string) error {
	_, err := a.c.RecallMessage(ctx, &sdkv1.RecallMessageRequest{Platform: platform, MessageId: messageID}, a.opts...)
	return err
}

func (a grpcHostCaller) GetConfig(ctx context.Context, pluginName, pluginID string) (map[string]any, error) {
	resp, err := a.c.GetConfig(ctx, &sdkv1.GetConfigRequest{PluginName: pluginName, PluginId: pluginID}, a.opts...)
	if err != nil {
		return nil, err
	}
	return unmarshalMap(resp.GetConfigJson()), nil
}

func (a grpcHostCaller) SetConfig(ctx context.Context, pluginName, pluginID string, cfg map[string]any) error {
	_, err := a.c.SetConfig(ctx, &sdkv1.SetConfigRequest{PluginName: pluginName, PluginId: pluginID, ConfigJson: marshalJSON(cfg)}, a.opts...)
	return err
}

func (a grpcHostCaller) ChatLLM(ctx context.Context, req *sdk.ChatLLMRequest) (string, error) {
	resp, err := a.c.ChatLLM(ctx, hostChatLLMToProto(req), a.opts...)
	if err != nil {
		return "", err
	}
	return resp.GetText(), nil
}

func (a grpcHostCaller) React(ctx context.Context, platform, sessionID, messageID, emoji string) error {
	_, err := a.c.React(ctx, &sdkv1.ReactRequest{Platform: platform, SessionId: sessionID, MessageId: messageID, Emoji: emoji}, a.opts...)
	return err
}

func (a grpcHostCaller) TextToImage(ctx context.Context, text, templateName string) (string, error) {
	resp, err := a.c.TextToImage(ctx, &sdkv1.TextToImageRequest{Text: text, TemplateName: templateName}, a.opts...)
	if err != nil {
		return "", err
	}
	return imageBytesOrBase64(resp.GetImageBase64(), resp.GetImageBytes()), nil
}

func (a grpcHostCaller) HtmlRender(ctx context.Context, template, data, options string) (string, error) {
	resp, err := a.c.HtmlRender(ctx, &sdkv1.HtmlRenderRequest{Template: template, Data: data, Options: options}, a.opts...)
	if err != nil {
		return "", err
	}
	return imageBytesOrBase64(resp.GetImageBase64(), resp.GetImageBytes()), nil
}

func (a grpcHostCaller) GetCurrConversationID(ctx context.Context, unifiedMsgOrigin string) string {
	resp, err := a.c.GetCurrConversationID(ctx, &sdkv1.ConversationIDRequest{UnifiedMsgOrigin: unifiedMsgOrigin}, a.opts...)
	if err != nil {
		return ""
	}
	return resp.GetCid()
}

func (a grpcHostCaller) NewConversation(ctx context.Context, unifiedMsgOrigin, platformID, personaID string) string {
	resp, err := a.c.NewConversation(ctx, &sdkv1.NewConversationRequest{UnifiedMsgOrigin: unifiedMsgOrigin, PlatformId: platformID, PersonaId: personaID}, a.opts...)
	if err != nil {
		return ""
	}
	return resp.GetCid()
}

func (a grpcHostCaller) GetConversation(ctx context.Context, unifiedMsgOrigin, cid string, createIfNotExists bool) map[string]any {
	resp, err := a.c.GetConversation(ctx, &sdkv1.GetConversationRequest{UnifiedMsgOrigin: unifiedMsgOrigin, ConversationId: cid, CreateIfNotExists: createIfNotExists}, a.opts...)
	if err != nil {
		return nil
	}
	return unmarshalMap(resp.GetConversationJson())
}

func (a grpcHostCaller) GetConversations(ctx context.Context, unifiedMsgOrigin string) []map[string]any {
	resp, err := a.c.GetConversations(ctx, &sdkv1.GetConversationsRequest{UnifiedMsgOrigin: unifiedMsgOrigin}, a.opts...)
	if err != nil {
		return nil
	}
	out := make([]map[string]any, 0, len(resp.GetConversationsJson()))
	for _, b := range resp.GetConversationsJson() {
		out = append(out, unmarshalMap(b))
	}
	return out
}

func (a grpcHostCaller) DeleteConversation(ctx context.Context, unifiedMsgOrigin, cid string) error {
	_, err := a.c.DeleteConversation(ctx, &sdkv1.DeleteConversationRequest{UnifiedMsgOrigin: unifiedMsgOrigin, ConversationId: cid}, a.opts...)
	return err
}

func (a grpcHostCaller) SwitchConversation(ctx context.Context, unifiedMsgOrigin, cid string) error {
	_, err := a.c.SwitchConversation(ctx, &sdkv1.SwitchConversationRequest{UnifiedMsgOrigin: unifiedMsgOrigin, ConversationId: cid}, a.opts...)
	return err
}

func (a grpcHostCaller) UpdateConversationTitle(ctx context.Context, unifiedMsgOrigin, cid, title string) error {
	_, err := a.c.UpdateConversationTitle(ctx, &sdkv1.UpdateConversationTitleRequest{UnifiedMsgOrigin: unifiedMsgOrigin, ConversationId: cid, Title: title}, a.opts...)
	return err
}

func (a grpcHostCaller) UpdateConversationPersonaID(ctx context.Context, unifiedMsgOrigin, cid, personaID string) error {
	_, err := a.c.UpdateConversationPersonaID(ctx, &sdkv1.UpdateConversationPersonaRequest{UnifiedMsgOrigin: unifiedMsgOrigin, ConversationId: cid, PersonaId: personaID}, a.opts...)
	return err
}

func (a grpcHostCaller) GetPersonas(ctx context.Context) []map[string]any {
	resp, err := a.c.GetPersonas(ctx, &sdkv1.Empty{}, a.opts...)
	if err != nil {
		return nil
	}
	out := make([]map[string]any, 0, len(resp.GetPersonasJson()))
	for _, b := range resp.GetPersonasJson() {
		out = append(out, unmarshalMap(b))
	}
	return out
}

func (a grpcHostCaller) GetDefaultPersona(ctx context.Context, umo string) map[string]any {
	resp, err := a.c.GetDefaultPersona(ctx, &sdkv1.GetDefaultPersonaRequest{Umo: umo}, a.opts...)
	if err != nil {
		return nil
	}
	return unmarshalMap(resp.GetPersonaJson())
}

func (a grpcHostCaller) GetPersonaTree(ctx context.Context) (folders []map[string]any, personas []map[string]any) {
	resp, err := a.c.GetPersonaTree(ctx, &sdkv1.Empty{}, a.opts...)
	if err != nil {
		return nil, nil
	}
	for _, b := range resp.GetFoldersJson() {
		folders = append(folders, unmarshalMap(b))
	}
	for _, b := range resp.GetPersonasJson() {
		personas = append(personas, unmarshalMap(b))
	}
	return folders, personas
}

func (a grpcHostCaller) ResolveSelectedPersona(ctx context.Context, umo, conversationPersonaID, platformName string, providerSettings map[string]any) (personaID, personaName, personaPrompt, forceAppliedPersonaID string, isDefault bool) {
	resp, err := a.c.ResolveSelectedPersona(ctx, &sdkv1.ResolvePersonaRequest{
		Umo:                   umo,
		ConversationPersonaId: conversationPersonaID,
		PlatformName:          platformName,
		ProviderSettingsJson:  marshalJSON(providerSettings),
	}, a.opts...)
	if err != nil {
		return "", "", "", "", false
	}
	return resp.GetPersonaId(), resp.GetPersonaName(), resp.GetPersonaPrompt(), resp.GetForceAppliedPersonaId(), resp.GetIsDefault()
}

func (a grpcHostCaller) ListProviders(ctx context.Context, capability string) []map[string]any {
	resp, err := a.c.ListProviders(ctx, &sdkv1.ListProvidersRequest{Capability: capability}, a.opts...)
	if err != nil {
		return nil
	}
	out := make([]map[string]any, 0, len(resp.GetProvidersJson()))
	for _, b := range resp.GetProvidersJson() {
		out = append(out, unmarshalMap(b))
	}
	return out
}

func (a grpcHostCaller) GetUsingProvider(ctx context.Context, umo, capability string) map[string]any {
	resp, err := a.c.GetUsingProvider(ctx, &sdkv1.GetUsingProviderRequest{Umo: umo, Capability: capability}, a.opts...)
	if err != nil {
		return nil
	}
	return unmarshalMap(resp.GetProviderJson())
}

func (a grpcHostCaller) SetProvider(ctx context.Context, umo, providerID, capability string) error {
	_, err := a.c.SetProvider(ctx, &sdkv1.SetProviderRequest{Umo: umo, ProviderId: providerID, Capability: capability}, a.opts...)
	return err
}

func (a grpcHostCaller) GetProviderModels(ctx context.Context, providerID string) []string {
	resp, err := a.c.GetProviderModels(ctx, &sdkv1.GetProviderModelsRequest{ProviderId: providerID}, a.opts...)
	if err != nil {
		return nil
	}
	return resp.GetModels()
}

func (a grpcHostCaller) GetPluginRegistry(ctx context.Context) []map[string]any {
	resp, err := a.c.GetPluginRegistry(ctx, &sdkv1.Empty{}, a.opts...)
	if err != nil {
		return nil
	}
	out := make([]map[string]any, 0, len(resp.GetStarsJson()))
	for _, b := range resp.GetStarsJson() {
		out = append(out, unmarshalMap(b))
	}
	return out
}

func (a grpcHostCaller) GetStar(ctx context.Context, name string) map[string]any {
	resp, err := a.c.GetStar(ctx, &sdkv1.GetStarRequest{Name: name}, a.opts...)
	if err != nil {
		return nil
	}
	return unmarshalMap(resp.GetStarJson())
}

func (a grpcHostCaller) SetPluginEnabled(ctx context.Context, pluginName string, enabled bool) error {
	_, err := a.c.SetPluginEnabled(ctx, &sdkv1.SetPluginEnabledRequest{PluginName: pluginName, Enabled: enabled}, a.opts...)
	return err
}

func (a grpcHostCaller) InstallPlugin(ctx context.Context, repo string) error {
	_, err := a.c.InstallPlugin(ctx, &sdkv1.InstallPluginRequest{Repo: repo}, a.opts...)
	return err
}

func (a grpcHostCaller) UninstallPlugin(ctx context.Context, pluginName string) error {
	_, err := a.c.UninstallPlugin(ctx, &sdkv1.UninstallPluginRequest{PluginName: pluginName}, a.opts...)
	return err
}

func (a grpcHostCaller) ListCommandDescriptors(ctx context.Context) []map[string]any {
	resp, err := a.c.ListCommandDescriptors(ctx, &sdkv1.Empty{}, a.opts...)
	if err != nil {
		return nil
	}
	out := make([]map[string]any, 0, len(resp.GetDescriptorsJson()))
	for _, b := range resp.GetDescriptorsJson() {
		out = append(out, unmarshalMap(b))
	}
	return out
}

func (a grpcHostCaller) ListPlatforms(ctx context.Context) []map[string]any {
	resp, err := a.c.ListPlatforms(ctx, &sdkv1.Empty{}, a.opts...)
	if err != nil {
		return nil
	}
	out := make([]map[string]any, 0, len(resp.GetPlatformsJson()))
	for _, b := range resp.GetPlatformsJson() {
		out = append(out, unmarshalMap(b))
	}
	return out
}

func (a grpcHostCaller) RegisterSessionWait(ctx context.Context, _, umo string, timeoutSeconds int32) string {
	resp, err := a.c.RegisterSessionWait(ctx, &sdkv1.RegisterSessionWaitRequest{Umo: umo, TimeoutSeconds: timeoutSeconds}, a.opts...)
	if err != nil {
		return ""
	}
	return resp.GetWaitId()
}

func (a grpcHostCaller) UnregisterSessionWait(ctx context.Context, waitID string) {
	_, _ = a.c.UnregisterSessionWait(ctx, &sdkv1.UnregisterSessionWaitRequest{WaitId: waitID}, a.opts...)
}

func (a grpcHostCaller) RegisterBridgeHook(ctx context.Context, pluginName, hookName string) error {
	_, err := a.c.RegisterBridgeHook(ctx, &sdkv1.BridgeHookRequest{PluginName: pluginName, HookName: hookName}, a.opts...)
	return err
}

func (a grpcHostCaller) UnregisterBridgeHook(ctx context.Context, pluginName, hookName string) error {
	_, err := a.c.UnregisterBridgeHook(ctx, &sdkv1.BridgeHookRequest{PluginName: pluginName, HookName: hookName}, a.opts...)
	return err
}

func (a grpcHostCaller) CreateBlob(ctx context.Context, data []byte, mimeType, filename string, ttlSeconds int32) (*sdk.FileReference, error) {
	resp, err := a.c.CreateBlob(ctx, &sdkv1.CreateBlobRequest{Data: data, MimeType: mimeType, Filename: filename, TtlSeconds: ttlSeconds}, a.opts...)
	if err != nil {
		return nil, err
	}
	return protoToFileRef(resp.GetFile()), nil
}

func (a grpcHostCaller) ReadBlob(ctx context.Context, handleID string, offset int64, limit int32) ([]byte, bool, int64, error) {
	resp, err := a.c.ReadBlob(ctx, &sdkv1.ReadBlobRequest{HandleId: handleID, Offset: offset, Limit: limit}, a.opts...)
	if err != nil {
		return nil, false, 0, err
	}
	return resp.GetData(), resp.GetEof(), resp.GetTotalSize(), nil
}

func (a grpcHostCaller) GetBlobInfo(ctx context.Context, handleID string) (*sdk.FileReference, error) {
	resp, err := a.c.GetBlobInfo(ctx, &sdkv1.GetBlobInfoRequest{HandleId: handleID}, a.opts...)
	if err != nil {
		return nil, err
	}
	return protoToFileRef(resp.GetFile()), nil
}

func (a grpcHostCaller) ReleaseBlob(ctx context.Context, handleID string) error {
	_, err := a.c.ReleaseBlob(ctx, &sdkv1.ReleaseBlobRequest{HandleId: handleID}, a.opts...)
	return err
}

func (a grpcHostCaller) ListSkills(ctx context.Context) []map[string]any {
	resp, err := a.c.ListSkills(ctx, &sdkv1.Empty{}, a.opts...)
	if err != nil {
		return nil
	}
	out := make([]map[string]any, 0, len(resp.GetSkillsJson()))
	for _, b := range resp.GetSkillsJson() {
		out = append(out, unmarshalMap(b))
	}
	return out
}

func (a grpcHostCaller) SetSkillActive(ctx context.Context, name string, active bool) error {
	_, err := a.c.SetSkillActive(ctx, &sdkv1.SetSkillActiveRequest{Name: name, Active: active}, a.opts...)
	return err
}

func (a grpcHostCaller) DeleteSkill(ctx context.Context, name string) error {
	_, err := a.c.DeleteSkill(ctx, &sdkv1.DeleteSkillRequest{Name: name}, a.opts...)
	return err
}

func (a grpcHostCaller) ListSkillsV2(ctx context.Context, activeOnly bool, runtime string, showSandboxPath bool) []map[string]any {
	resp, err := a.c.ListSkillsV2(ctx, &sdkv1.ListSkillsV2Request{ActiveOnly: activeOnly, Runtime: runtime, ShowSandboxPath: showSandboxPath}, a.opts...)
	if err != nil {
		return nil
	}
	out := make([]map[string]any, 0, len(resp.GetSkillsJson()))
	for _, b := range resp.GetSkillsJson() {
		out = append(out, unmarshalMap(b))
	}
	return out
}

func (a grpcHostCaller) GetPlatformMessageHistory(ctx context.Context, platformID, userID string, limit int32) []map[string]any {
	resp, err := a.c.GetPlatformMessageHistory(ctx, &sdkv1.GetPMHistoryRequest{PlatformId: platformID, UserId: userID, Limit: limit}, a.opts...)
	if err != nil {
		return nil
	}
	out := make([]map[string]any, 0, len(resp.GetRecordsJson()))
	for _, b := range resp.GetRecordsJson() {
		out = append(out, unmarshalMap(b))
	}
	return out
}

func (a grpcHostCaller) InsertPlatformMessageHistory(ctx context.Context, platformID, userID, senderID string, content any, llmCheckpointID string, maxMessages int32) map[string]any {
	resp, err := a.c.InsertPlatformMessageHistory(ctx, &sdkv1.InsertPMHistoryRequest{
		PlatformId:      platformID,
		UserId:          userID,
		SenderId:        senderID,
		ContentJson:     marshalJSON(content),
		LlmCheckpointId: llmCheckpointID,
		MaxMessages:     maxMessages,
	}, a.opts...)
	if err != nil {
		return nil
	}
	return unmarshalMap(resp.GetRecordJson())
}

func (a grpcHostCaller) UpdatePlatformMessageHistory(ctx context.Context, id int64, content any, llmCheckpointID string) error {
	_, err := a.c.UpdatePlatformMessageHistory(ctx, &sdkv1.UpdatePMHistoryRequest{Id: id, ContentJson: marshalJSON(content), LlmCheckpointId: llmCheckpointID}, a.opts...)
	return err
}

func (a grpcHostCaller) DeletePlatformMessageHistory(ctx context.Context, id int64) error {
	_, err := a.c.DeletePlatformMessageHistory(ctx, &sdkv1.DeletePMHistoryRequest{Id: id}, a.opts...)
	return err
}

func (a grpcHostCaller) KBRetrieve(ctx context.Context, query string, kbNames []string, topKFusion, topMFinal int) (contextText string, resultsJSON string, err error) {
	resp, err := a.c.KBRetrieve(ctx, &sdkv1.KBRetrieveRequest{Query: query, KbNames: kbNames, TopKFusion: int32(topKFusion), TopMFinal: int32(topMFinal)}, a.opts...)
	if err != nil {
		return "", "", err
	}
	return resp.GetContextText(), resp.GetResultsJson(), nil
}

func (a grpcHostCaller) KBUploadFromURL(ctx context.Context, kbNameOrID, url string, chunkSize, chunkOverlap int) error {
	_, err := a.c.KBUploadFromURL(ctx, &sdkv1.KBUploadFromURLRequest{KbId: kbNameOrID, Url: url, ChunkSize: int32(chunkSize), ChunkOverlap: int32(chunkOverlap)}, a.opts...)
	return err
}

func (a grpcHostCaller) KBListKBs(ctx context.Context) []map[string]any {
	resp, err := a.c.KBListKBs(ctx, &sdkv1.Empty{}, a.opts...)
	if err != nil {
		return nil
	}
	out := make([]map[string]any, 0, len(resp.GetKbsJson()))
	for _, b := range resp.GetKbsJson() {
		out = append(out, unmarshalMap(b))
	}
	return out
}

func (a grpcHostCaller) RegisterFileToken(ctx context.Context, path string, timeoutSec int32) (string, error) {
	resp, err := a.c.RegisterFileToken(ctx, &sdkv1.RegisterFileTokenRequest{Path: path, TimeoutSec: timeoutSec}, a.opts...)
	if err != nil {
		return "", err
	}
	return resp.GetToken(), nil
}

func (a grpcHostCaller) CronCreate(ctx context.Context, spec *sdk.CronCreateSpec) (map[string]any, error) {
	var payload []byte
	if spec != nil {
		payload = marshalJSON(spec.Payload)
	}
	var name, jobType, cronExpression, timezone, description, runAt string
	var enabled, runOnce bool
	if spec != nil {
		name, jobType, cronExpression, timezone = spec.Name, spec.JobType, spec.CronExpression, spec.Timezone
		description, runAt, enabled, runOnce = spec.Description, spec.RunAt, spec.Enabled, spec.RunOnce
	}
	resp, err := a.c.CronCreate(ctx, &sdkv1.CronCreateRequest{
		Name:           name,
		JobType:        jobType,
		CronExpression: cronExpression,
		Timezone:       timezone,
		PayloadJson:    payload,
		Description:    description,
		Enabled:        enabled,
		RunOnce:        runOnce,
		RunAt:          runAt,
	}, a.opts...)
	if err != nil {
		return nil, err
	}
	return unmarshalMap(resp.GetJobJson()), nil
}

func (a grpcHostCaller) CronUpdate(ctx context.Context, jobID string, fields map[string]any) (map[string]any, error) {
	resp, err := a.c.CronUpdate(ctx, &sdkv1.CronUpdateRequest{JobId: jobID, FieldsJson: marshalJSON(fields)}, a.opts...)
	if err != nil {
		return nil, err
	}
	return unmarshalMap(resp.GetJobJson()), nil
}

func (a grpcHostCaller) CronDelete(ctx context.Context, jobID string) error {
	_, err := a.c.CronDelete(ctx, &sdkv1.CronDeleteRequest{JobId: jobID}, a.opts...)
	return err
}

func (a grpcHostCaller) CronList(ctx context.Context, jobType string) []map[string]any {
	resp, err := a.c.CronList(ctx, &sdkv1.CronListRequest{JobType: jobType}, a.opts...)
	if err != nil {
		return nil
	}
	out := make([]map[string]any, 0, len(resp.GetJobsJson()))
	for _, b := range resp.GetJobsJson() {
		out = append(out, unmarshalMap(b))
	}
	return out
}

func (a grpcHostCaller) CronRunNow(ctx context.Context, jobID string) error {
	_, err := a.c.CronRunNow(ctx, &sdkv1.CronRunNowRequest{JobId: jobID}, a.opts...)
	return err
}

func (a grpcHostCaller) McpListTools(ctx context.Context) []map[string]any {
	resp, err := a.c.McpListTools(ctx, &sdkv1.Empty{}, a.opts...)
	if err != nil {
		return nil
	}
	out := make([]map[string]any, 0, len(resp.GetToolsJson()))
	for _, b := range resp.GetToolsJson() {
		out = append(out, unmarshalMap(b))
	}
	return out
}

func (a grpcHostCaller) McpCallTool(ctx context.Context, server, toolName string, args map[string]any) (result map[string]any, text string, isError bool, err error) {
	resp, err := a.c.McpCallTool(ctx, &sdkv1.McpCallToolRequest{Server: server, ToolName: toolName, ArgumentsJson: marshalJSON(args)}, a.opts...)
	if err != nil {
		return nil, "", false, err
	}
	return unmarshalMap(resp.GetResultJson()), resp.GetText(), resp.GetIsError(), nil
}
