// Code generated by scripts/gen_core_ifaces.py. DO NOT EDIT.

package grpctransport

import (
	"context"

	sdk "github.com/WaterGodFurina/Astrbot-go-plugin-sdk"
	sdkv1 "github.com/WaterGodFurina/Astrbot-go-plugin-sdk/gen/sdkv1"
	sdkv1grpc "github.com/WaterGodFurina/Astrbot-go-plugin-sdk/gen/sdkv1grpc"
	grpc "google.golang.org/grpc"
)

// grpcHostCaller adapts the generated variadic HostServiceClient to the
// core sdk.HostService (non-variadic), so the plugin-side Host wrappers run
// unchanged over gRPC.
type grpcHostCaller struct {
	c    sdkv1grpc.HostServiceClient
	opts []grpc.CallOption
}

var _ sdk.HostService = grpcHostCaller{}

func (a grpcHostCaller) CallAction(arg0 context.Context, arg1 *sdkv1.CallActionRequest) (*sdkv1.CallActionResponse, error) {
	return a.c.CallAction(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) SendMessage(arg0 context.Context, arg1 *sdkv1.SendMessageRequest) (*sdkv1.Empty, error) {
	return a.c.SendMessage(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) RecallMessage(arg0 context.Context, arg1 *sdkv1.RecallMessageRequest) (*sdkv1.Empty, error) {
	return a.c.RecallMessage(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) GetConfig(arg0 context.Context, arg1 *sdkv1.GetConfigRequest) (*sdkv1.GetConfigResponse, error) {
	return a.c.GetConfig(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) SetConfig(arg0 context.Context, arg1 *sdkv1.SetConfigRequest) (*sdkv1.Empty, error) {
	return a.c.SetConfig(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) ChatLLM(arg0 context.Context, arg1 *sdkv1.ChatLLMRequest) (*sdkv1.ChatLLMResponse, error) {
	return a.c.ChatLLM(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) React(arg0 context.Context, arg1 *sdkv1.ReactRequest) (*sdkv1.Empty, error) {
	return a.c.React(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) TextToImage(arg0 context.Context, arg1 *sdkv1.TextToImageRequest) (*sdkv1.TextToImageResponse, error) {
	return a.c.TextToImage(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) HtmlRender(arg0 context.Context, arg1 *sdkv1.HtmlRenderRequest) (*sdkv1.HtmlRenderResponse, error) {
	return a.c.HtmlRender(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) GetCurrConversationID(arg0 context.Context, arg1 *sdkv1.ConversationIDRequest) (*sdkv1.ConversationIDResponse, error) {
	return a.c.GetCurrConversationID(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) NewConversation(arg0 context.Context, arg1 *sdkv1.NewConversationRequest) (*sdkv1.ConversationIDResponse, error) {
	return a.c.NewConversation(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) GetConversation(arg0 context.Context, arg1 *sdkv1.GetConversationRequest) (*sdkv1.ConversationResponse, error) {
	return a.c.GetConversation(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) GetConversations(arg0 context.Context, arg1 *sdkv1.GetConversationsRequest) (*sdkv1.ConversationsResponse, error) {
	return a.c.GetConversations(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) DeleteConversation(arg0 context.Context, arg1 *sdkv1.DeleteConversationRequest) (*sdkv1.Empty, error) {
	return a.c.DeleteConversation(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) SwitchConversation(arg0 context.Context, arg1 *sdkv1.SwitchConversationRequest) (*sdkv1.Empty, error) {
	return a.c.SwitchConversation(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) UpdateConversationTitle(arg0 context.Context, arg1 *sdkv1.UpdateConversationTitleRequest) (*sdkv1.Empty, error) {
	return a.c.UpdateConversationTitle(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) UpdateConversationPersonaID(arg0 context.Context, arg1 *sdkv1.UpdateConversationPersonaRequest) (*sdkv1.Empty, error) {
	return a.c.UpdateConversationPersonaID(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) GetPersonas(arg0 context.Context, arg1 *sdkv1.Empty) (*sdkv1.PersonasResponse, error) {
	return a.c.GetPersonas(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) GetDefaultPersona(arg0 context.Context, arg1 *sdkv1.GetDefaultPersonaRequest) (*sdkv1.PersonaResponse, error) {
	return a.c.GetDefaultPersona(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) GetPersonaTree(arg0 context.Context, arg1 *sdkv1.Empty) (*sdkv1.PersonaTreeResponse, error) {
	return a.c.GetPersonaTree(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) ResolveSelectedPersona(arg0 context.Context, arg1 *sdkv1.ResolvePersonaRequest) (*sdkv1.ResolvePersonaResponse, error) {
	return a.c.ResolveSelectedPersona(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) ListProviders(arg0 context.Context, arg1 *sdkv1.ListProvidersRequest) (*sdkv1.ProvidersResponse, error) {
	return a.c.ListProviders(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) GetUsingProvider(arg0 context.Context, arg1 *sdkv1.GetUsingProviderRequest) (*sdkv1.ProviderResponse, error) {
	return a.c.GetUsingProvider(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) SetProvider(arg0 context.Context, arg1 *sdkv1.SetProviderRequest) (*sdkv1.Empty, error) {
	return a.c.SetProvider(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) GetProviderModels(arg0 context.Context, arg1 *sdkv1.GetProviderModelsRequest) (*sdkv1.ProviderModelsResponse, error) {
	return a.c.GetProviderModels(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) GetPluginRegistry(arg0 context.Context, arg1 *sdkv1.Empty) (*sdkv1.StarsResponse, error) {
	return a.c.GetPluginRegistry(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) GetStar(arg0 context.Context, arg1 *sdkv1.GetStarRequest) (*sdkv1.StarResponse, error) {
	return a.c.GetStar(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) SetPluginEnabled(arg0 context.Context, arg1 *sdkv1.SetPluginEnabledRequest) (*sdkv1.Empty, error) {
	return a.c.SetPluginEnabled(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) InstallPlugin(arg0 context.Context, arg1 *sdkv1.InstallPluginRequest) (*sdkv1.Empty, error) {
	return a.c.InstallPlugin(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) UninstallPlugin(arg0 context.Context, arg1 *sdkv1.UninstallPluginRequest) (*sdkv1.Empty, error) {
	return a.c.UninstallPlugin(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) ListCommandDescriptors(arg0 context.Context, arg1 *sdkv1.Empty) (*sdkv1.CommandDescriptorsResponse, error) {
	return a.c.ListCommandDescriptors(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) ListPlatforms(arg0 context.Context, arg1 *sdkv1.Empty) (*sdkv1.PlatformsResponse, error) {
	return a.c.ListPlatforms(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) RegisterSessionWait(arg0 context.Context, arg1 *sdkv1.RegisterSessionWaitRequest) (*sdkv1.RegisterSessionWaitResponse, error) {
	return a.c.RegisterSessionWait(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) UnregisterSessionWait(arg0 context.Context, arg1 *sdkv1.UnregisterSessionWaitRequest) (*sdkv1.Empty, error) {
	return a.c.UnregisterSessionWait(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) RegisterBridgeHook(arg0 context.Context, arg1 *sdkv1.BridgeHookRequest) (*sdkv1.Empty, error) {
	return a.c.RegisterBridgeHook(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) UnregisterBridgeHook(arg0 context.Context, arg1 *sdkv1.BridgeHookRequest) (*sdkv1.Empty, error) {
	return a.c.UnregisterBridgeHook(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) CreateBlob(arg0 context.Context, arg1 *sdkv1.CreateBlobRequest) (*sdkv1.CreateBlobResponse, error) {
	return a.c.CreateBlob(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) ReadBlob(arg0 context.Context, arg1 *sdkv1.ReadBlobRequest) (*sdkv1.ReadBlobResponse, error) {
	return a.c.ReadBlob(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) GetBlobInfo(arg0 context.Context, arg1 *sdkv1.GetBlobInfoRequest) (*sdkv1.GetBlobInfoResponse, error) {
	return a.c.GetBlobInfo(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) ReleaseBlob(arg0 context.Context, arg1 *sdkv1.ReleaseBlobRequest) (*sdkv1.Empty, error) {
	return a.c.ReleaseBlob(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) ListSkills(arg0 context.Context, arg1 *sdkv1.Empty) (*sdkv1.SkillsResponse, error) {
	return a.c.ListSkills(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) SetSkillActive(arg0 context.Context, arg1 *sdkv1.SetSkillActiveRequest) (*sdkv1.Empty, error) {
	return a.c.SetSkillActive(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) DeleteSkill(arg0 context.Context, arg1 *sdkv1.DeleteSkillRequest) (*sdkv1.Empty, error) {
	return a.c.DeleteSkill(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) GetPlatformMessageHistory(arg0 context.Context, arg1 *sdkv1.GetPMHistoryRequest) (*sdkv1.PMHistoryRecordsResponse, error) {
	return a.c.GetPlatformMessageHistory(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) InsertPlatformMessageHistory(arg0 context.Context, arg1 *sdkv1.InsertPMHistoryRequest) (*sdkv1.PMHistoryRecordResponse, error) {
	return a.c.InsertPlatformMessageHistory(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) UpdatePlatformMessageHistory(arg0 context.Context, arg1 *sdkv1.UpdatePMHistoryRequest) (*sdkv1.Empty, error) {
	return a.c.UpdatePlatformMessageHistory(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) DeletePlatformMessageHistory(arg0 context.Context, arg1 *sdkv1.DeletePMHistoryRequest) (*sdkv1.Empty, error) {
	return a.c.DeletePlatformMessageHistory(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) KBRetrieve(arg0 context.Context, arg1 *sdkv1.KBRetrieveRequest) (*sdkv1.KBRetrieveResponse, error) {
	return a.c.KBRetrieve(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) KBUploadFromURL(arg0 context.Context, arg1 *sdkv1.KBUploadFromURLRequest) (*sdkv1.Empty, error) {
	return a.c.KBUploadFromURL(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) KBListKBs(arg0 context.Context, arg1 *sdkv1.Empty) (*sdkv1.KBListResponse, error) {
	return a.c.KBListKBs(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) ListSkillsV2(arg0 context.Context, arg1 *sdkv1.ListSkillsV2Request) (*sdkv1.SkillsResponse, error) {
	return a.c.ListSkillsV2(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) RegisterFileToken(arg0 context.Context, arg1 *sdkv1.RegisterFileTokenRequest) (*sdkv1.RegisterFileTokenResponse, error) {
	return a.c.RegisterFileToken(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) CronCreate(arg0 context.Context, arg1 *sdkv1.CronCreateRequest) (*sdkv1.CronJobResponse, error) {
	return a.c.CronCreate(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) CronUpdate(arg0 context.Context, arg1 *sdkv1.CronUpdateRequest) (*sdkv1.CronJobResponse, error) {
	return a.c.CronUpdate(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) CronDelete(arg0 context.Context, arg1 *sdkv1.CronDeleteRequest) (*sdkv1.Empty, error) {
	return a.c.CronDelete(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) CronList(arg0 context.Context, arg1 *sdkv1.CronListRequest) (*sdkv1.CronJobsResponse, error) {
	return a.c.CronList(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) CronRunNow(arg0 context.Context, arg1 *sdkv1.CronRunNowRequest) (*sdkv1.Empty, error) {
	return a.c.CronRunNow(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) McpListTools(arg0 context.Context, arg1 *sdkv1.Empty) (*sdkv1.McpToolsResponse, error) {
	return a.c.McpListTools(arg0, arg1, a.opts...)
}

func (a grpcHostCaller) McpCallTool(arg0 context.Context, arg1 *sdkv1.McpCallToolRequest) (*sdkv1.McpCallToolResponse, error) {
	return a.c.McpCallTool(arg0, arg1, a.opts...)
}
