//go:build windows

// Code generated by scripts/gen_cabi_dispatch.py. DO NOT EDIT.

package native

import (
	"context"

	sdk "github.com/WaterGodFurina/Astrbot-go-plugin-sdk"
	sdkv1 "github.com/WaterGodFurina/Astrbot-go-plugin-sdk/gen/sdkv1"
	"google.golang.org/protobuf/proto"
)

// cabiCall unmarshals req into the method's request type, invokes svc and
// marshals the response back to protobuf bytes. Covers every PluginService
// method so the C ABI surface stays 1:1 with the Go interface.
func cabiCall(svc sdk.PluginService, method string, req []byte) ([]byte, error) {
	switch method {
	case "Register":
		in := &sdkv1.RegisterRequest{}
		if len(req) > 0 {
			if err := proto.Unmarshal(req, in); err != nil {
				return nil, err
			}
		}
		out, err := svc.Register(context.Background(), in)
		if err != nil {
			return nil, err
		}
		return proto.Marshal(out)
	case "HandleCommand":
		in := &sdkv1.HandleCommandRequest{}
		if len(req) > 0 {
			if err := proto.Unmarshal(req, in); err != nil {
				return nil, err
			}
		}
		out, err := svc.HandleCommand(context.Background(), in)
		if err != nil {
			return nil, err
		}
		return proto.Marshal(out)
	case "HandleFilter":
		in := &sdkv1.HandleFilterRequest{}
		if len(req) > 0 {
			if err := proto.Unmarshal(req, in); err != nil {
				return nil, err
			}
		}
		out, err := svc.HandleFilter(context.Background(), in)
		if err != nil {
			return nil, err
		}
		return proto.Marshal(out)
	case "HandleHook":
		in := &sdkv1.HandleHookRequest{}
		if len(req) > 0 {
			if err := proto.Unmarshal(req, in); err != nil {
				return nil, err
			}
		}
		out, err := svc.HandleHook(context.Background(), in)
		if err != nil {
			return nil, err
		}
		return proto.Marshal(out)
	case "HandleLLMRequest":
		in := &sdkv1.HandleLLMRequestRequest{}
		if len(req) > 0 {
			if err := proto.Unmarshal(req, in); err != nil {
				return nil, err
			}
		}
		out, err := svc.HandleLLMRequest(context.Background(), in)
		if err != nil {
			return nil, err
		}
		return proto.Marshal(out)
	case "HandleTool":
		in := &sdkv1.HandleToolRequest{}
		if len(req) > 0 {
			if err := proto.Unmarshal(req, in); err != nil {
				return nil, err
			}
		}
		out, err := svc.HandleTool(context.Background(), in)
		if err != nil {
			return nil, err
		}
		return proto.Marshal(out)
	case "ListTools":
		in := &sdkv1.PluginRef{}
		if len(req) > 0 {
			if err := proto.Unmarshal(req, in); err != nil {
				return nil, err
			}
		}
		out, err := svc.ListTools(context.Background(), in)
		if err != nil {
			return nil, err
		}
		return proto.Marshal(out)
	case "ListWebApis":
		in := &sdkv1.PluginRef{}
		if len(req) > 0 {
			if err := proto.Unmarshal(req, in); err != nil {
				return nil, err
			}
		}
		out, err := svc.ListWebApis(context.Background(), in)
		if err != nil {
			return nil, err
		}
		return proto.Marshal(out)
	case "HandleWebRequest":
		in := &sdkv1.HandleWebRequestRequest{}
		if len(req) > 0 {
			if err := proto.Unmarshal(req, in); err != nil {
				return nil, err
			}
		}
		out, err := svc.HandleWebRequest(context.Background(), in)
		if err != nil {
			return nil, err
		}
		return proto.Marshal(out)
	case "HealthCheck":
		in := &sdkv1.Empty{}
		if len(req) > 0 {
			if err := proto.Unmarshal(req, in); err != nil {
				return nil, err
			}
		}
		out, err := svc.HealthCheck(context.Background(), in)
		if err != nil {
			return nil, err
		}
		return proto.Marshal(out)
	case "SetLogLevel":
		in := &sdkv1.SetLogLevelRequest{}
		if len(req) > 0 {
			if err := proto.Unmarshal(req, in); err != nil {
				return nil, err
			}
		}
		out, err := svc.SetLogLevel(context.Background(), in)
		if err != nil {
			return nil, err
		}
		return proto.Marshal(out)
	case "FeedSessionWait":
		in := &sdkv1.FeedSessionWaitRequest{}
		if len(req) > 0 {
			if err := proto.Unmarshal(req, in); err != nil {
				return nil, err
			}
		}
		out, err := svc.FeedSessionWait(context.Background(), in)
		if err != nil {
			return nil, err
		}
		return proto.Marshal(out)
	case "GetConfigSchema":
		in := &sdkv1.PluginRef{}
		if len(req) > 0 {
			if err := proto.Unmarshal(req, in); err != nil {
				return nil, err
			}
		}
		out, err := svc.GetConfigSchema(context.Background(), in)
		if err != nil {
			return nil, err
		}
		return proto.Marshal(out)
	case "Cleanup":
		in := &sdkv1.PluginRef{}
		if len(req) > 0 {
			if err := proto.Unmarshal(req, in); err != nil {
				return nil, err
			}
		}
		out, err := svc.Cleanup(context.Background(), in)
		if err != nil {
			return nil, err
		}
		return proto.Marshal(out)
	case "FeedCronJob":
		in := &sdkv1.FeedCronJobRequest{}
		if len(req) > 0 {
			if err := proto.Unmarshal(req, in); err != nil {
				return nil, err
			}
		}
		out, err := svc.FeedCronJob(context.Background(), in)
		if err != nil {
			return nil, err
		}
		return proto.Marshal(out)
	case "ManagePlugin":
		in := &sdkv1.ManagePluginRequest{}
		if len(req) > 0 {
			if err := proto.Unmarshal(req, in); err != nil {
				return nil, err
			}
		}
		out, err := svc.ManagePlugin(context.Background(), in)
		if err != nil {
			return nil, err
		}
		return proto.Marshal(out)
	default:
		return nil, sdk.Errorf(sdk.CodeUnimplemented, "unknown method %q", method)
	}
}
