#!/usr/bin/env python3
"""Generate the grpc-free core service interfaces + the gRPC reverse-call adapter.

The core `sdk` package must not import google.golang.org/grpc / go-plugin. But
it needs:
  * `PluginService`  - host->plugin operations (implemented by serviceServer)
  * `HostService`    - plugin->host reverse calls (implemented by hostServiceServer)

The generated `gen/sdkv1grpc` package has these interfaces but with grpc types
(`*grpc.ClientConn` etc. only in the client side; the server side is clean apart
from the generated marker, which we strip). We copy the server interfaces into
core, qualifying message types with `sdkv1.`, and generate an adapter that turns
the variadic generated HostServiceClient into the core HostService.

Run after split_grpc_pkg.py.
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GRPC = os.path.join(ROOT, "gen", "sdkv1grpc", "plugin_grpc.pb.go")
MSG = os.path.join(ROOT, "gen", "sdkv1", "plugin.pb.go")
OUT_IFACES = os.path.join(ROOT, "service_iface.go")
OUT_ADAPTER = os.path.join(ROOT, "transport", "grpc", "host_adapter.go")
GO_PKG = "github.com/WaterGodFurina/Astrbot-go-plugin-sdk"

types = []
with open(MSG, encoding="utf-8") as f:
    for line in f:
        m = re.match(r"^type ([A-Z]\w*) ", line)
        if m:
            types.append(m.group(1))
# Longest first so `RegisterRequest` wins over `Register`.
types.sort(key=len, reverse=True)
type_re = re.compile(r"\b(" + "|".join(re.escape(t) for t in types) + r")\b")


def qualify(s: str) -> str:
    # Avoid double-qualifying `sdkv1.Xxx`.
    s = re.sub(r"sdkv1\.(\w+)", r"\1", s)
    return type_re.sub(r"sdkv1.\1", s)


def extract_server(service: str):
    with open(GRPC, encoding="utf-8") as f:
        text = f.read()
    marker = "type %sServer interface {" % service
    i = text.index(marker)
    block = text[i : text.index("\n}\n", i)]
    methods = []
    for line in block.splitlines()[1:]:
        line = line.rstrip()
        if not line.startswith("\t") or line.lstrip().startswith("//"):
            continue
        m = re.match(r"^\t([A-Z]\w*)\((.*)\) \((.*)\)$", line)
        if not m:
            continue
        methods.append((m.group(1), m.group(2), m.group(3)))
    return methods


def split_params(params):
    out, depth, cur = [], 0, ""
    for ch in params:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == "," and depth == 0:
            out.append(cur.strip())
            cur = ""
        else:
            cur += ch
    if cur.strip():
        out.append(cur.strip())
    return out


def emit_iface(name, methods, comment):
    lines = [comment]
    lines.append("type %s interface {" % name)
    for mname, params, results in methods:
        lines.append("\t%s(%s) (%s)" % (mname, qualify(params), qualify(results)))
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


plugin_methods = extract_server("PluginService")
host_methods = extract_server("HostService")
if not plugin_methods or not host_methods:
    raise SystemExit("failed to extract server interfaces")

with open(OUT_IFACES, "w", encoding="utf-8") as f:
    f.write("// Code generated by scripts/gen_core_ifaces.py. DO NOT EDIT.\n\n")
    f.write("package sdk\n\n")
    f.write("import (\n\t\"context\"\n\n")
    f.write('\tsdkv1 "%s"\n' % (GO_PKG + "/gen/sdkv1"))
    f.write(")\n\n")
    f.write(emit_iface("PluginService", plugin_methods,
                       "// PluginService is the host->plugin operation surface, implemented by serviceServer."))
    f.write("\n")
    f.write(emit_iface("HostService", host_methods,
                       "// HostService is the plugin->host reverse-call surface. The gRPC transport\n"
                       "// adapts the generated client to it; the Native transport uses hostServiceServer\n"
                       "// in-process directly."))

# Adapter: generated variadic HostServiceClient -> core HostService.
os.makedirs(os.path.dirname(OUT_ADAPTER), exist_ok=True)
with open(OUT_ADAPTER, "w", encoding="utf-8") as f:
    f.write("// Code generated by scripts/gen_core_ifaces.py. DO NOT EDIT.\n\n")
    f.write("package grpctransport\n\n")
    f.write("import (\n\t\"context\"\n\n")
    f.write('\tsdk "%s"\n' % GO_PKG)
    f.write('\tsdkv1 "%s"\n' % (GO_PKG + "/gen/sdkv1"))
    f.write('\tsdkv1grpc "%s"\n' % (GO_PKG + "/gen/sdkv1grpc"))
    f.write('\tgrpc "google.golang.org/grpc"\n')
    f.write(")\n\n")
    f.write("// grpcHostCaller adapts the generated variadic HostServiceClient to the\n")
    f.write("// core sdk.HostService (non-variadic), so the plugin-side Host wrappers run\n")
    f.write("// unchanged over gRPC.\n")
    f.write("type grpcHostCaller struct {\n\tc    sdkv1grpc.HostServiceClient\n\topts []grpc.CallOption\n}\n\n")
    f.write("var _ sdk.HostService = grpcHostCaller{}\n\n")
    for mname, params, results in host_methods:
        ps = split_params(params)
        # normalise param names (generated uses `in`, `ctx`; some use `_`).
        named = []
        call_args = []
        i = 0
        for p in ps:
            parts = p.split()
            typ = parts[0]
            nm = parts[1] if len(parts) > 1 else ("arg%d" % i)
            i += 1
            named.append("%s %s" % (nm, qualify(typ)))
            call_args.append(nm)
        f.write("func (a grpcHostCaller) %s(%s) (%s) {\n" % (
            mname, ", ".join(named), qualify(results)))
        f.write("\treturn a.c.%s(%s, a.opts...)\n" % (mname, ", ".join(call_args)))
        f.write("}\n\n")

import subprocess

subprocess.run(["gofmt", "-w", OUT_IFACES, OUT_ADAPTER], check=False)
print("wrote service_iface.go (%d host, %d plugin methods) and transport/grpc/host_adapter.go"
      % (len(host_methods), len(plugin_methods)))
