#!/usr/bin/env python3
"""Generate the Windows C-ABI method dispatcher from service_iface.go.

The Windows Native transport (c-shared DLL) crosses the C ABI with sdkv1
protobuf bytes. The dispatcher maps a method name to its request/response
proto types and calls the corresponding sdk.PluginService method after
proto.Unmarshal. Generated (not hand-written) so it stays in sync with the
PluginService interface.
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IFACE = os.path.join(ROOT, "service_iface.go")
OUT = os.path.join(ROOT, "native", "cabi_dispatch_windows.go")
PKG = "github.com/WaterGodFurina/Astrbot-go-plugin-sdk"

methods = []
in_iface = False
with open(IFACE, encoding="utf-8") as f:
    for line in f:
        if line.startswith("type PluginService interface {"):
            in_iface = True
            continue
        if in_iface and line.startswith("}"):
            break
        if not in_iface:
            continue
        m = re.match(r"\t([A-Z]\w*)\(context\.Context, \*sdkv1\.(\w+)\) \(\*sdkv1\.(\w+), error\)", line)
        if m:
            methods.append(m.groups())

if len(methods) < 10:
    raise SystemExit("failed to parse PluginService methods (%d found)" % len(methods))

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8") as f:
    f.write("//go:build windows\n\n")
    f.write("// Code generated by scripts/gen_cabi_dispatch.py. DO NOT EDIT.\n\n")
    f.write("package native\n\n")
    f.write("import (\n\t\"context\"\n\n")
    f.write('\tsdk "%s"\n' % PKG)
    f.write('\tsdkv1 "%s"\n' % (PKG + "/gen/sdkv1"))
    f.write("\t\"google.golang.org/protobuf/proto\"\n")
    f.write(")\n\n")
    f.write("// cabiCall unmarshals req into the method's request type, invokes svc and\n")
    f.write("// marshals the response back to protobuf bytes. Covers every PluginService\n")
    f.write("// method so the C ABI surface stays 1:1 with the Go interface.\n")
    f.write("func cabiCall(svc sdk.PluginService, method string, req []byte) ([]byte, error) {\n")
    f.write("\tswitch method {\n")
    for name, req, resp in methods:
        f.write('\tcase "%s":\n' % name)
        f.write("\t\tin := &sdkv1.%s{}\n" % req)
        f.write("\t\tif len(req) > 0 {\n\t\t\tif err := proto.Unmarshal(req, in); err != nil {\n\t\t\t\treturn nil, err\n\t\t\t}\n\t\t}\n")
        f.write("\t\tout, err := svc.%s(context.Background(), in)\n" % name)
        f.write("\t\tif err != nil {\n\t\t\treturn nil, err\n\t\t}\n")
        f.write("\t\treturn proto.Marshal(out)\n")
    f.write("\tdefault:\n")
    f.write('\t\treturn nil, sdk.Errorf(sdk.CodeUnimplemented, "unknown method %%q", method)\n')
    f.write("\t}\n}\n")

print("wrote native/cabi_dispatch_windows.go (%d methods)" % len(methods))
