#!/usr/bin/env python3
"""Split the generated gRPC service code out of gen/sdkv1 into gen/sdkv1grpc.

Why: the Native plugin build must not compile/link google.golang.org/grpc. The
generated `plugin_grpc.pb.go` imports grpc; if it stays in the `sdkv1` package,
then importing `sdkv1` (for message types) drags grpc into every build.

`protoc-gen-go-grpc` always emits into the message package (same go_package), so
instead of rewriting ~130 qualified type references we move the file to a new
package and add type aliases for every generated type. Unqualified references in
the moved file then resolve through the aliases.

Run after `buf generate`:
    buf generate && python3 scripts/split_grpc_pkg.py
"""
import os
import re
import shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MSG_DIR = os.path.join(ROOT, "gen", "sdkv1")
GRPC_DIR = os.path.join(ROOT, "gen", "sdkv1grpc")
GO_PKG = "github.com/WaterGodFurina/Astrbot-go-plugin-sdk/gen/sdkv1"

src_pb = os.path.join(MSG_DIR, "plugin.pb.go")
src_grpc = os.path.join(MSG_DIR, "plugin_grpc.pb.go")
if not os.path.exists(src_pb):
    raise SystemExit("plugin.pb.go not found; run `buf generate` first")

os.makedirs(GRPC_DIR, exist_ok=True)

# 1) Collect every exported top-level generated type (messages + enums).
types = []
with open(src_pb, encoding="utf-8") as f:
    for line in f:
        m = re.match(r"^type ([A-Z]\w*) ", line)
        if m:
            types.append(m.group(1))

# 2) Aliases file: unqualified names in the moved grpc file resolve here.
with open(os.path.join(GRPC_DIR, "aliases.go"), "w", encoding="utf-8") as f:
    f.write("// Code generated by scripts/split_grpc_pkg.py. DO NOT EDIT.\n")
    f.write("package sdkv1grpc\n\n")
    f.write('import sdkv1 "%s"\n\n' % GO_PKG)
    for t in types:
        f.write("type %s = sdkv1.%s\n" % (t, t))

# 3) Move the grpc file and retarget its package (idempotent: if it was already
# moved, only the aliases above are refreshed).
if os.path.exists(src_grpc):
    with open(src_grpc, encoding="utf-8") as f:
        body = f.read()
    body = re.sub(r"^package sdkv1$", "package sdkv1grpc", body, count=1, flags=re.M)
    with open(os.path.join(GRPC_DIR, "plugin_grpc.pb.go"), "w", encoding="utf-8") as f:
        f.write(body)
    os.remove(src_grpc)
    print("moved plugin_grpc.pb.go -> gen/sdkv1grpc (aliases: %d types)" % len(types))
else:
    print("plugin_grpc.pb.go already moved; refreshed %d aliases" % len(types))

# 4) Drop the generated `mustEmbedUnimplemented...` requirement from the server
# interfaces. The core package (grpc-free) implements these interfaces
# structurally; the unexported marker would force it to embed grpc types.
grpc_out = os.path.join(GRPC_DIR, "plugin_grpc.pb.go")
with open(grpc_out, encoding="utf-8") as f:
    lines = f.readlines()
kept = [l for l in lines if not re.match(r"^\tmustEmbedUnimplemented\w+\(\)\s*$", l)]
if len(kept) != len(lines):
    with open(grpc_out, "w", encoding="utf-8") as f:
        f.writelines(kept)
    print("stripped %d mustEmbed requirement(s)" % (len(lines) - len(kept)))
